In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],
               [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

2

In [7]:
arr.shape

(2, 3)

In [8]:
arr.size

6

In [9]:
arr.dtype

dtype('int32')

## Array Creation

In [12]:
arr = np.array([[1,2,3],[4,5,6]], dtype='float')

In [13]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
arr = np.array((1, 2, 3))
print(arr)

[1 2 3]


In [18]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
arr = np.ones((2,1))
print(arr)

[[1.]
 [1.]]


In [27]:
arr = np.full((3,3), 6, dtype='complex')
print(arr)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [31]:
e = np.random.random((2,2))
print(e)

[[0.30842374 0.97553204]
 [0.22233871 0.48122684]]


In [35]:
seq_arr = np.arange(0,30, 5) 
print(seq_arr)

[ 0  5 10 15 20 25]


In [38]:
g = np.linspace(0,5,10) #10 elements equally spaced
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [41]:
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2, 2, 3)
print(arr,"\n\nNew Array:\n",newarr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]] 

New Array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print(flarr)

[1 2 3 4 5 6]


## Array Indexing

In [48]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [50]:
temp = arr[:2, ::2]
print(temp)

[[-1.  0.]
 [ 4.  6.]]


In [51]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]] #Elements at indices (0, 3), (1, 2), (2, 1), (3, 0)
print(temp)

[4. 6. 0. 3.]


In [52]:
cond = arr>0 #positive elements in the array 
print(arr[cond])

[2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


## Operations on Single array

In [61]:
a = np.array([1, 2, 5, 3])
print("a+1\n",a+1)
print("\na-2\n",a-2)
print("\na**2\n",a**2)
a *= 2 
print("\na*=2\n",a)
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("\nTranspose:\n",a.T) # transpose
print("\nOriginal:\n",a)

a+1
 [2 3 6 4]

a-2
 [-1  0  3  1]

a**2
 [ 1  4 25  9]

a*=2
 [ 2  4 10  6]

Transpose:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]

Original:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]


## Unary Operators

In [62]:
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]])

In [63]:
print(arr.max()) # max element

9


In [64]:
print(arr.max(axis=1)) #row-wise max element

[6 7 9]


In [65]:
print(arr.min(axis=0)) #column-wise min element

[1 1 2]


In [67]:
print(arr.sum())

38


In [70]:
print(arr.cumsum(axis=1)) #cumulative sum along each row

[[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


## Binary Operators

In [71]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[4, 3], 
              [2, 1]])

In [72]:
print(a+b) #Sum

[[5 5]
 [5 5]]


In [76]:
print(a*b) # Array Multiplicaion

[[4 6]
 [6 4]]


In [75]:
print(a.dot(b)) # Matrix multiplication

[[ 8  5]
 [20 13]]


## Universal functions

In [78]:
a = np.array([0, np.pi/2, np.pi])
print(a)

[0.         1.57079633 3.14159265]


In [83]:
print(np.sin(a)) # sin of array elements

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [81]:
print(np.exp(a)) #exponent of array elements

[ 1.          4.81047738 23.14069263]


In [84]:
print(np.sqrt(a)) #sqrt of array elements

[0.         1.25331414 1.77245385]


## Sorting array

In [85]:
a = np.array([[1, 4, 2],
              [3, 4,6],
              [0, -1, 5]])

In [90]:
print(np.sort(a, axis=None)) # by default axis = 1 

[-1  0  1  2  3  4  4  5  6]


In [93]:
print(np.sort(a, axis=1)) #row wise sort of array elements

[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [97]:
print(np.sort(a, axis=0, kind = 'mergesort'))

[[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [98]:
# example to show sorting of structured array
## set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

In [99]:
#values to put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

In [101]:
arr = np.array(values, dtype = dtypes)
print(arr)

[(b'Hrithik', 2009, 8.5) (b'Ajay', 2008, 8.7) (b'Pankaj', 2008, 7.9)
 (b'Aakash', 2009, 9. )]


In [103]:
print(np.sort(arr, order='name'))#sort according to name

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
[(b'Hrithik', 2009, 8.5) (b'Ajay', 2008, 8.7) (b'Pankaj', 2008, 7.9)
 (b'Aakash', 2009, 9. )]


In [109]:
print(np.sort(arr, order = ['grad_year', 'cgpa']))

[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


## Stacking and Splitting

In [110]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [114]:
print(np.vstack((a,b))) #vertical stack

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [119]:
print(np.hstack((a,b))) #horizontal stack

[[1 2 5 6]
 [3 4 7 8]]


In [123]:
c = [5,6]
print(np.column_stack((a,c)))

[[1 2 5]
 [3 4 6]]


In [129]:
print(np.concatenate((a, b), 1))

[[1 2 5 6]
 [3 4 7 8]]


In [130]:
a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])

In [138]:
print(np.hsplit(a,2)) #horizontal split

[array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]


In [143]:
np.vsplit(a,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [144]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [145]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

3.0


In [148]:
print(np.mean(b))

3.0


In [149]:
print(np.mean(a, axis = 0))

[4.  4.  2.5 2. ]


In [150]:
print(np.mean(a, axis = 1))

[2.5  3.75]


In [151]:
c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [152]:
w = np.array([1,1,1,1,1])

In [157]:
print(np.average(c, weights = w))# weighted mean => n1*w1 + n2*w2 / n1+n2

2.4


In [160]:
#Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

1.854723699099141


In [163]:
#In-Built Satndard Deviation function
dev = np.std(c)
print(dev)

1.854723699099141


In [164]:
#Variance
print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004


## Random Module

In [165]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [174]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[12  6 13 11  5 14  8  9  7 10]


In [175]:
#Returns values from a Standard Normal Distributions
a = np.random.randn(2,3)
print(a)

[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]


In [176]:
a = np.random.randint(5,10,3)
print(a)

[7 9 6]


In [177]:
#Randoly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

4
